In [ ]:
from google.colab import files
files.upload()

Saving cleaned_air.csv.zip to cleaned_air.csv.zip

{'cleaned_air.csv.zip': b'PK\x03\x04-\x00\x00\x08\x08\x00W|\xc3X\x1d\xdf\x8b\xa0\xff\xff\xff\xff\xff\xff\xff\xff\x0f\x00\x14\x00cleaned_air.csv\x01\x00\x10\x00\xa5\xd3"\x00\x00\x00\x00\x00.\xec\x02\x00\x00\x00\x00\x00\xd4}\xd9r\x1bW\x96\xed\xbb"\xf2\x1f\x14~>Q\xf7\xcc\xc3#H\x90m\x89\x92\x8bU\x10eW\xbf\xb1l\xb6\x8dk\x99tP\xd2\xad\xae\xfe\xfa\xbb\xd7\xc9L \x93\x02\x88\x1c\xceN\xa9\x1d\x1d\xd1\x12\xecB"\xcf\xb0\xc7\xb5\xd7\xfa\xeb\x9fw\x8f\xb7\x9f\xb6\xf7\xbf\xbe\\m\x1f?l\xef\xef\xc4\x17\x9f\xbc|\xb5z\xb7zy\xfe\xf0\xcb\x9d\xb8\xfe\xfc\xcf\x0f\xdb\x8f\xbf\xdd\xfd\xb2\xfb\xaf\xbf\xf8\xa4\xf3_\xff\xc7\xc5__n>\xff\xf1\xc7\xed\xe3\xbf\xf3\x9f\xff~\xf7\xeb\xf6\xe1^\xbc\xb9\xbd\xff\xa5\xf9\xfa\x9f\x1fo\xff\xeb\xd3\xcbw\xff\xfe\xf3N\xec\xfev\xf6\xf0\xcb\xbf\x9f|\xf4\xf6\xf6\xfe\xf3\x7f\xdd\xfe\xfc\xe9\xf3\xe3\xddc\xe7Sz\xc6\x87\xdd\xb7\x9d?|\xbe\xff$\xde=|\xba\xfd\xf0\x12\x9f\xd1/\xfa\xf1n\xfb\xebo\x9f\xaa\x17\x9b\xdf\xff\xfd\xe3\xdd\xc7O\xed/\xfc(\xfe\xfaWqs\xbf\xfd\xb4\xff\xd1\x1f\xc5\xcdJ\xbc\xba\xfft\xf7xO\xaf\xfep\x7f\xfbA\x9c\xdf\xde\xdf\xfer+\xaeo?~\xbc\xbb\xff\x95\x9e[\xffz\xfa\xf6\xd7w\x9f\xc4\xd9\xc3\x1f\xff\xbc}\xfceK\x9f\x9f\xff\xfd\xb5\x16F\ne\x95\xa4\x7f\xaa\x17\xf4\x9d/\x9b\xff\xf5\xea\\\xf4\xffv\xe2\x19?\xdc>>>\xfc+/\x01\xfe\x87\xff\xfc\xfcQ\xac\x8c\xa6\xef\xd6N\xa8\x10bH!V/^\xdf\xfey{\xbf\xff\xe9\xaf\xdf\x88/?\xe9?h\xf5q\xdb}\xcc\x8f\xdb_\xee\xea\x87\x9c=\xdc\xd1\xe2\x89\xb3\x10L~\x07\xefu\xfd\x12\xdf\x9d\xff\xf5z\xb5\xff\xc6\x97\xaf\xee\x7f\xfe\xcbw\xe2\xfc\xad8\xfa/\x9e\xbc\xda\xdd\xfd\xa7GZ\xac\xd5\x1fw\x8f\xdb\x9f\x8f\xbd\xe3\xee\xf1&\t#lR\x01\xcf\xfe\xfe\x81\xf6\xf3\xeaa\x7f\x02?\xbe|\xb3\xfd\x03\xfb%\xbe\xffI<\xffo\x07\xbe\xf7nq]\xa2\x97\x16\xc1H\x15\x94\xae^\\n\xef\xefo\xb7t\xc8\xfe!:\x7f\xec\x7f\xe9\xc5\xe7\xc7\x07:\x9d\xcf~\xad1\x82\xde((i\x82\xaf^\xfc\xf8\xd7\x1f\xf1c\xc5\x8f?\x8a\xce\x1f\'}+6Ik\xe3\xbc\xa3\x85:p\x88\xc7\x9f\xeb\xc3\xfb\x11\x85\x97"\xd2\x91\xcb\xa7a\xf3\xf0\xf9\xd3o\xff\xea\xdd\xa1\x1f\x7f\x10\x87?]?\xfcA\x1fm\x7f\x167\x9b\x01O\xd1\x91\xf6]&\xa9|~\x0e}~\xfb\xe7\xc3\xe3\xdd\xfe\x1b7\x7f\x13\x87?}5\xfe\x84kl\xb6\xf4>\xbf\xd3\xfa\xee\xc3\xa7[|#\x1d\x1f|\xe5\xfa\x8d8\xf4\xd1\xc1\xb79\xf0\xf5\x9e\xbe>\x88\xe8m}\x7f\xa6l\xcd\xe9w\x881\xbf\x83\x92\xcd-=\x7f\xf8\xe3O\xfa\xef\xf7\xdfy~-\x9a\x1b\xd71\x07\xab\xd5\x91\xd7\xe8\x99\xb4\x8b?\xfe\xf9xK\x1f^\xa8@\xc6\x86\xb6\x06\x87\xd7:o\xb9^\x866D):g\xce\x04={G\x8eY\x15\x1d\xb5\xb0\xd6\xb8\x98\xcf\xd7\xc5\x1f[\xf2m\xf4=\x17W\xa2\xfb\xe7W#\xad\x06\xed\x03]D\x8do\xd5\n&\xff\xd0\x9a\x8f\xd8\x88\x83\xbf\xdei\x11\xb0\x11~\xe7U.\x1fo\xef\x7f&\xbfx)\xfa\x7f\x1boI\xda\x17p:9M\xdf\xfe\xfe\xe1\xc3\xed\xe3\xb6s\x90\xfea\xc5\xa1\xcf\xfaOz{\xf7\xdf\xdb\x9f\x1f\x86\xf8\xaf \xb4%\xe7\xe5R\xf5\xe2\x8a.r\xbd(\xcd\x9e^]\x88C\x9f\xbd\x1ay\x9c,\x9dX:\xb8R\x9b\xfan\xbc\xdf>\xfe\xba\xa5\xef\xfc\xf4\xe1\xf6\x1e\x0b\xfe~#\x0e|4x\xe9\xf6w0\tGw];\xed\xf2s.\x1f\x1f\xe8\xcb\xee\x1e\xf7\xebt\x99\xc4\xc1\x0fO\xef}w\xcd\x9c\x13Qy\xabb\x81\xf3u\xc8\x97hr$\xc2\x06\xdfX\xde\xcf\xf7u\x08\xf5\xf8\xef\x8e\x95\xfd\x878\xf6\xf9z\xf896A\xc0fy\x1ds`\x81\xd5\xcf\x87*\xc7\x0e\xdf\t\xf7\x0fq\xe8\xb3\xee\x03.\x1fs$w\xc4\xf0j\xa1\x95p\xe4\xbe\xeb\xed(\xe4\xc1\x11\x18\x082\x7f\xc6\x85B\x97\xafg\xf8\x8c \xa3W\xff\xe2\xf3\xdf\xb6\xf7\xb7/\xb33\xa5/\x12\xe7\xff)\xbe\xfcd\xece\xa0CJ\x8fp\xed\x19\x9db\xc0\x07\xbe\t\xad\x93\xd1\xbe1R\xc3\x9e\xb3\x1eu\x0f\x94\xb1d\x06cR\x8e\xeev\xac&\xbd\xcb\xe0@;\xd0\xa3d\xb2I[_\xef\xfa\xf5\xed\xcf\xdb\xff\xda\xfe\xdc\x86\x98/\x7f\xf9\xe7\xed\xcb\xcb\xed\xff\xdd\xe2a\xff\xba\xfd7\xdd\xeb\xd7b\xe8\x7f\xf7d\x13?\x7fD\x84\xbc\xbd}\xf9\x7f^\xfe\xf5g2\x7f\xa7\x9c\x0e\xddXZk\x17mP\xae\x9c\xb3\xdc\xbf=]"\x11]\xf0\xc5\xbc\xcd\xfe\x98P\x82\x04O&\rb\xec\xd7\xb7\xff\xf3?/W\xffo\x9b\xbfA\xfc\xedj\\\x8a\xf4L\x1a\x06+C!X\x88>\xa7\x11\x87\xd2\xbe\x15\xd9\x99\xdfo;\x16s3:4\xf2N\xd8\x18\xb4\x96\x8e\xc1\x98YK\x9b@\xf7\x89)\x93T\x82\xce\xb8\xb1FZ\x06\x0f\xb9{\x8c\xa5\x84J\x98\x94|\n\xa9*f\x13\xf6q\x11eAdu\xa2\xb4\xca\xcf]\xa6\xc36\xcd\x92{o\xbe{\xf3\xaf\xed\xc7\x8f\x94{|zy\xb3Y\xe1\x87~\xf1\xc1\x01\xd3\xfc\xcc\x16\xaf\x94\xb6\xe4X\x82\x0e\x8es\x0b(S$\xefE\x99"\xc2\xf7\xda\x9d\\\xdc~\xc4\xb7\x88\xb77\xe2\x8b\x0f\x06\xba\x97\xae)\x82{Q.R\x88\xc2\xb1\xc5\x9a\xbe<\xe4`\xce\xef\xf7\xf8\x87\xbb\x7f\xbd\xfc\xcf\xbb[Z\x97_\xc4\x0f\xff)\x0e|4\xcd\xc2\xf6R\xc4\x9c\xfb\xb8\xfa\xfe\xfd\x8dv\xa0\xbe\xca\xd9\x84\xff\xedR|\xf9\xc9\xccG\xd2\x85\xd7\x9e\xb2R\'\x9b\xf7\xbc{\xa4e\xcaa\xf5\xea\xad\xe8\xffmD\xf0\xdd\r\xbe\x14\x05zM\x1a?\xac\x106\xc0"\xf6\r/E\xf7\x92\xa2o\x93L\xf3\x12\xc5\xc2\xd5\xfd\xd6\xe0=lc\x17\xdf\xad\xceW\xe2\x1d\xfe\xaf\xfe\xffSJO\xab\x8e\xd7\xb7\x89.\xa4\xf2*\xaajRxq:\x1e#\x0fH??\xc8"\xcbs\xac\x96\xa2B\xa4\xf3\xebM\x1dV^\xbc_\xed\xce\xe9\xd9\xdf\xc5\x93\xbf\x8e~\x01#\xa2G\xba`\xed\x98\xa34\xc6\x99\xf7\x0b\x10Z\xc4\x94l\xb4\xf3\xac\xcb\x91\xd0\x98\xbc\xb8\tcB\xe3\xc1\xdfN\x1b\xad5,\x97\xa2\xe4\x9a\xe3\x01\xde"\x96\x92\x8d\x85z\xf7\xf9\xf1\xf7\xed\xc7\xdf\xf6_\xf5\xeeJ\x1c\xfal\xb0\x07\xe9nx\xaf \xccU\x02\xc4Z\xc5ltcl\x9e\xc4\x98\x8a\xe6\xb2\x875>e\xef\xfb\xe6\xf3\x7f}\xfa\xed\xf6\xfe\xe3\xed\xcb\xff\xb8{\xfc\xa3{\xf7\xde|/\x9e\xfd\x97\x83\xd7sgfv%\xa3\x94b\xb2\xb5C{u\xff\x0by\x8a\xb6z\xbdz%\x0e~\xf8j\xbc\xad\x81\x7fv\xa1\xb9\xaa\xb5\xb7\xdf\xfd\xfa\xf3W\xe2\xcbO\xc6\x051\xb5\xdb\xa28\xc6\xa5X?c\xc9\x95\xa4\xf0\x12\'\x93\x12\xfe\x94P|{\xf5\xf3\x1d\xfc\xff-\xad\xdd\xc5\xf7\x97\xe2\x92\xde\xe6\xcbO\xee\xc7\x9e\x7foP\xb5r\xd6\xeeCq\xfe\xf8\x83\xc2\x1e\xa1Ms\xb7\xd7\xa5\xcb\xa1\x148\xa3\x91\x94\x83\x01\xa6\'h\xd4\xf9(?JM8s~K;\xff\xef6;\x16\xe7?\x89/?\x19x\xbew\xfbO\xb1?,\xac\xa6t\xc6\x9b\x94C&\xfc\xd8_\xe9_^\xbc\x12\xfd\xbf\xbd\x1a}\xba\x0cj{\xe4{\x82\x8e\xaat\xa8\xa1PSR&\x90\x0f\xaa&\x05\x1a\x03c\xbeH\xeeM$Z\x9e\x84=x\xf5O\xfaq\xb7\xe2\xd5\x99\xd8\xffi\xb7\xa7\x83\x96dW*Lqb7\xe0\xed\xf6\x97_>\xdc\xe5\x94\xe3\xa4\xdb\x81a1:\xd5\x07hF\xb5\xf8y\x03\x16s\xa8\x9fd\x13\x06\x9c\xce\x91\x06{h\x94\xf7\x84s\xb5a|\xf7\xdb\xc3\x1f\x940\x9c?<\xfc\xbe_\x9e\xb7\xef\xc4\xb1\xcf\'\x1c\xd8fwl\x0c(U\xb2e\x94\xf5c\xa2\xa2\xcb\xad\xab\xf2\xa7w\xf7 \x94\xbeEP2%9\xed1\xc3j!t\x17Q\x0e\x89\xc98O\xb7\xf1\xfb\xdb\x7f\xddn\xb7]\xdf\xf4\xfdJ\x1c\xfc\xf0\xd49\xe8\xae\x18L\x95\xf1\x81,UZ$\x9bDl\x1b(\x97i\xca\xbe\xd7\xbfm?l\xff\xfc\x93~\xf9\xfe\r\xae\xff.\x8e|<\xd0\x0e\x1f\x8d\x10\xa7\xec\xd5\x10OL^\x91\x12\x02c\x9d,\x93>\x1d^\xb7$Ll\x96\xadx\x0e\x1e\x05"\\M\x1e\xc5\x96t\xbb\x87\xaf\xcc\x81\x12\xe7\xe0\xaa\xe7\xf1\xcc\x92\xae\x8a\xf5\xba\xb6i\x7f\xbf\xfb\xa5\x06\xf0\xd0\xca\xbc\xbc\xc0\x82\xfc\xf9\xb8\xfdH\xdf\xfb\xcf\xffFJ\xf7\xcc\xbf<\\\x07\xa5\x84\xe5\x9f\x0f/\xaf\xe9$\x90C\xfd\xf8\xf1\xfeV\x9c\xa3\x9e\xe0\x84\xd5nD\xae9\xa0l\xd1I1\xa5\xf0\x12\r\x1ei\x93\xca-\x9e\xb2Q\x04\x85\x10\xc2\xa8h\xc8.O\xbb\x19\xa7\xef\x1f.;\x05[\xb4+\x8d\x0fcY\'\xbay\x01mt+c\x90\x06\xed\xce\xbb\xfb\x9f\x7f{yvw\'\xce.E\xffo\xd3\xac\xd7n\xd1\\\xdd\xb4JF{\xab\xaa\xf2\xd1\xa9BbD\xef\xe3B\x13a\x0f\xbb*\xfd\xb7\x1ap\x1b\xe9\xae\xd0\xfe[\xca\xd1\xa3\x83\xaf\xa4\x15=\xfb\xf0\xf9ng\xe7\xcf\xbc8\xf0\xd1z\xc4}W\xb4)\x9a\x82\xbc(\x91\xa0T/~z\xd3~S\xdb\xa7\xd9\\\x88\x83\x1fN:\xca9\xd3S\x94\xabO<\xca\x9f\xc7\xbb1\xc0\\h\x15\xeb\x83}\xf5\xe6\xed\xcb\xbf?\xfc\x9b\x0e\xe7\xfa\xf3\xa7\x9f;\x95\x8d\xab7\xe2\xb9\x7f7\xf8e{y-=9\xea\xb6T\xc7\x97\xa5\x1b4Ib\x03\xb0\x9ar\x12\x87\x85S\x14\xe78\xe1cL\xb6y\x9d\x1c\xd8\n\xcafz\x7f\x19\xfb\xf3m]\xce\x90-\xdei\xcee=\\\xe5\xd2F\xc4\xb6\xcc\xb5*X1\xed\xde\xa2\x88\x8c\xccJ\xebbv4\xe5\x82\xc0^\x19A\x98&B*o\x08$\xb9\xfd\\lL\n\xbd\xf1\rS\x81\x1f\xb1?%\xc6.$\xa7jW\xb3-\x0e\xd4[u\xdc\x00\xe2JC\xd9kP\xed\xa1-\xd6\xde#\xdbbM\xbe\xe1,\xe5Y \xf4\xacH\xaa\xad\x9a\xfe\xceY&\xa7UB\xdb\xc5&\xad}\xc5\x16\x7f\xd7\x95K\xa5l\x13\x7f\x7f\xff\xf0\xb8\xfd\x9f\x87|\x1f\xc4\xdf~\x1a\x1e\\\x1e\x7f\x0btt\x13YB\xed\xaar\xcd\xca\xa3y\xca\xea\xc3\x87\x97?P\xfeS\xbfB\xbeu?|/\x0e\x7f:\xffY\xb7E\x82\xf1\xae97\x16\x9d\xb0\x14]\x90qL<6\xc4\xd9#\x04S\xc2I\x95\x92\x0eUq\x00\x02\xfdzK\xbb\x1d\x12\x8c\xd5\xd9\xe3\xf6S\xd3\xa7\xa8M\xdfJ\x1c\xf8h\xfc;<\x05g2\x81d\xe9\x11\ne\xf6dh\xd7\xe9\xfamV\x9b\x8e\xd9\xbb\x12O\xff>\xfeEl\x03\xf7\xa6\xbd\xf6J3^p\xda\x15\xd4\xc2T\x13n\xc1b\xd1\xcb\xee\xbf\xf5\xc7\x8d8\xf4\xd9\x88\x13\xd0\xed\xf7\xd0\x1dI\xd6\xd4\xb0\xc3\xe5"\xbb\'\xa5\x11\\\xe5n\x0f\xe4\xaf\xff)\x0e|4\xf0\xfa\xaf\x9e\xba.\xe7b\x8e\xcbof8\x97\xc3\xcb\x87\x14IRp$\x9d\xceX\xf3\xe2\xad\x97g\xab\xa6\xb9\x8d\xed\x1a\xcf\tsP\x14#\xe6\x85\x0e^R>[\x95\xf6\xca(\xc9\xca\xa6&;g\xf3O\xf6\xc4h}\xaci\x9eR\xd8\xbeu\x9f\x83C\x16S\xe3\x8f\x0b\xf6X\xba\x0b\xe6(=Q\x8e=?A\xed\xca\x8a\x10T\xcc\xa32\x19^\xf5\xb2\xffEo~\x12G>\x1e\xbfxO\x1d\xf4\xe5\xdd/w\xe8\xe0\\\xfc\xf7\x9f\x8fw\x1f?\x8a\xcb\x9f\xc4\x81\x8f\x0e\xd7\xad\x0e\x87\xfbV\xe6+Z\x7f\xfd\x15\xa5\xbd\x9f\xea,H\\Y\xf1\xe4\xaf\x83\xbf\xb6\x0f\x0b\\\xceh\x86n+\xa38\xd8\x11\xb9Q\x12^6}\xff\x9b\t\xeem`\x016!(\'?\xed\xf4\xb1\xa0|5?\x8aMp/\x14\x93\xe9\xc4\xecB#F\xd6\xb4\xb1\xc1\xcc\xcd\xbc\x8f\x87\x98\x14\x11\x04M\xa1\x14\xd7|\x03%\xc5\xc2)\xeb\xbc\x9c\x0cP\xb8\x1es\xcf\x97\x9eg\xec\xcf\xcf\xf1\xd4/$\xba\xc9V\xab\xc4\x81\x8a\xef\x85\x1cAh\x1f0\xdfZ,%\xe8\x9df\xbcI4\xa6\xec\x0cA\xef\tVG`\x14\x93\xaac\xa6\x19/q$*2\xc2\x9b\xa6e\xcd1\xcf\x01C\x1cEJa\xf8\x90\xcb\xe9h\x15P\x07\x11\xb5u\xc8\xc6V\x0c]\xb5\x08\xfb\x0e\xa8|}\t\xce\xcesW\x08_D>c\xf3\x97\xd5_^\xd2\xff\xe6\xfc/\xef\xff\x92\xc7%\xf2\xcf\xff\xbfdU-\x99\xe3\x11\xff\xed\x08\x8f\xd0\xbd;\xda\xef\x07tW\xa5\xd3t]\x17L\xc8\x00\xe9\x10\x8dw\xae\xdc3z\x17\x13\xf5\xcb\xe8\xbc\xcd\x03\x0fWL\x93ut\xf8(?\xd46\x19\xc9vC\xad\x17>\xe8\x14Kz\xb4\xee\xf7k\xf2\x06dal*b\x8f\x8fG~\xba\xad\x92]2\x8d\x05\xe6c+\xa5\xc5\x91*]\x89Co\x8c\x1e\xa0\xbdc\x01(\xad:\x11F\xd3\x93p\x0c8\xe5\x94\'\x13\xb4.\xb2\xd3\xc7~\x7f\x8d\xe3*yZ\xbb\xdf\xae\x11\xbd\xd0u\x8b\xbe\xdcm\xeb\xd9&O\xd1\x896\xc6yo\x95\xa9^\xf0\xf8\\\x18\rXA\xe3\xd8/\x84\xf2\x19\xfb\xb0.\xdf\x85Jh\xaf\xb4m\xa8\xedc\xe9r(J\x88\x9e\x8e\x12\x80u\x8c\xf6\xdb(`8\xc2q\xec\xfej~\xfeS\x0f\xdfy\xcc}UK\x8d\xce8\xa1\\\xf4i\x84[\x9a\xf9\xd0\x98\xf2Z\x1a\xd5\x16\xc1\xca\xc2F2\xfa1Q\xe4\x94\xa7\xf2\x17\x02\xdah\xe4\xe1._\xd2\x92L%\x98;\xf2\x96.\xbf\xab8\x1c.v\x82\x9e\xd0\xee\xc3\x1f\xe5\xec\xfc\xee\x11\x803\x8b6\xac\x1f\x16\xbfMt\x87V8\xa7\xc8iU/\x18g\xb4`\x94]\xb2,C\x93\x1a\xf9\t\x1d[\xee\xb5"\x83\x1f\xe9`\xd1\xad\xb7*L\xcc{/\x06\x96\xa3i\xf7q\x0f\x8f\xda\xcc\x93\x0f\x1a\xd1\xc8E\xc7J\xdb\x98\x1b\xde\xeb\xbb\xc2\xf1/9\x19\x8d\x1a\x98\xd7\xa9~\x9b\xf7|\xdc\x18O\xad\xe3Ca$e\xb2\xb9\xbfR\x8fxO\xd9\xfd\xd3\xfe\x92\xf2VKo\xe1\xdc\x8c\xc2\xe4\xe9\xa7\xf4F\x02\x99j\xf8t\x84\x8d5\xb6.B}_\xbco\x9f$%m\x0eM\x1b\x96\x0b\xf2\x05\xc9\x1a\xca].\xe4\x97)^\x8cnJ\xecM\x884l\xcb\x07\xfb*\xdfE\x01}\xc7PG\'\x17\x1eLSl|\xf3y\xd9\xa96\x85\xe2`p\nu\xefK^t\xa8\x16\xce\x06\xaf\xa3-\re\xa3wP\xa6\x9d\x92\xfe\xccI\x85\xa3\x10oi\x97\xbb\xdfg\x0b! n&\x18\xb01\x13;\xbd\xecb\xb5-\x9b$i8\x14r\x8e:e;\xc37\xed\x17E&?)\x11M\x1eZ\xa6\xee\x00\xfb\xf7<\xd3&\xf9h\x05\x95I"\xb9QN\xdd-\x9f\xd8\xc09e\x8f1\xe5\x17R\xd4\x1c\x89\x16\xb8\xd5tH\xce\xfa\xb2\xde\xb7k\xae\xb2\xbfR\xe4\xe2}\xe0GLv\x9fu3\xc3{\x1dN\x84\x8c\xb0\xe0W\x93\xd28=\xc2A\x8e\xb8\xef\xdd\xb2\xb6u\x82^\xa4\xc6\xe4\xae\x0b\x97t\xe8\xe8\xe6\xf9\xf9\xf9\x14;G.F\xdbt\x9c\xb6F\x83\xe3`\x80&(\x9a\xaf\x1b\xda\x0b\x80&\xba\xf7\xfd\xa6\xf4\xe6\xefN\xb2\xc2 \x16\x8a\xe8J\xaaj\xa1\xa1\xebIcl\x83\x0f\\\xcc\xf5\x95\x18Z@\xc8\x03\xdb<\xab\x12>v\x19\xe5Jch\x9f:\xf9K&~\xb0\r+\xff\x83#\xdb\x92T\xc8\xf7f\xd9\xf9\xc82\x96l\xef\xc2v\x14O\xb2b\x04\xfe\'\r\xc0\xbc\xf7\xa6\xdc\xbe\xaf\x9e\xc6\xa9-\x0b\xe9\xbb\xc2\xbc>`P\xf5^%\xcc\xf7\x15\x99\x82G\x99\xce9oc\xc5:gm\xe8\x97\xa3+`\xaa\xf2\xb5 Z\x13c\xac\xa0eix\x82\xcaA\xd4\xc8\x005\xd1\xc1\xaa\xa8W\xe5\x1e\xd9\xc8\x93\xe015\xc8\xe0\r#\xd75\nK\xde\xa7l|\x96a\x06\xc0Q\xd2:\xd8Tq\xd2\xfde\xdf\x10\xa4L2T\xff\x0b\xe9\xe6\x80\xa4p\xdec\xc4\xd98\x13\xf7.t\xc3I\xca\xca\xf1\x88\x90Y\xc8\x95M\xae\xaee,\x0f{\x0b^(\xfa\'\xe6U\xdc\xfc\xceY5w R\xb4\xd9\xba3\x0f\xc0\xe6\xd3\x97\xa2Mayu\x82(\xa2V\xd6j\x8e\x83\x0f\x9eEP\x13\xd0\xcdj\xb0=\x93\xa1\xf1\xa7\xde#\'\xa8\x14\xd6gL\xe9\x15S\xa7\xbb\x9dJm\xeb,\xac0\xdc@\x87O$\x97\xf1\xcbU\xf1\xe8.O]{i\xd3T\x02\xfe\xc1\xfd4\x1fE"\xa7d\xf1 \x9e!\xa6\xdc\x12\xd2*\xa60\xedU\x86\xe4\x10\x11HrQ\x93\xeea?JR\xfd\xe7\n7\xb9Q\x15\x0e\x9b\xb4\xc1\x1b\xfd\x0cx\xa2\xb5d\xf8\x96\xeb\x01d\xd2C\xff\xbbi\xd9q\xcf\xf8\xa9\x9a1\xcf\xab\xaa\x18\x88\xb1{\xfe\x94\xa6\x13\xa8\xa2\x02[\x86J\x9c\xd5\x05\x8cK[\x14\x7f(i*\xdbk\xef\xef\xa5\xb3\x99\xf0^\xc9h\x92)YM\xeemK\x87\xbd\x7f5=\xde>\xba+y\xc6\xc8&m\x9c\xad8\x1b\xfa\nX\xba@\x16\xdbW\x0c\xc3\xac\xc0\x19Zg\x80\x96\x1cv\xae\xd6\x0fcBz\x03\x8a@2ny\x13>\x94\xb9\x1b\xdd\xef\xa7\xa3\x04.\xea0_\xb2\xe6(|.\xa1\x88`\x82\xd5\x15\x13\xff\x81\x11\xa9Sl\xbd,Y5\x02[\xa2\x94\xb9v\xc0\xea\xea3\x90]\x87\x90F\xa0\x0e\x06/\x11(c=\x82\xb0\xa8\x1a\xdf\xc5\xd0+8Z\xc9[\x97.0\xa0~o\x0c];\xa5d\xe6\x1f\\}\x83\xb8\x7f\x19$P\x8a\xc5_\x1e\x14\x9b\x16H\x85(\xeb\x04\xec5\x07\xf7O\xd2\x00\xcbC\nB\xf2\xe1j\xad\x14\x0e\xac"h _-:\xa6\x8d$\xb2A\xdc2\x8cg\xd2M\xb3>\x8c\xa9\xf5O9h\xb0\x17d1\x9c\x0b<\xb35x\x13\xd4\xccM\x93\xb7Ml\xc1\x8e2\x15\xb8\x14\xaf\xb8(\x8b1<\x91|d\xda\x97\xaeu\xa2;\x8aa\xb3l\x9bX.O\xd3\xc4\xa2\\\xd7\xc4\xf2\xde\xc2 \xa8\x89FM_\xa9!\xf7\x90\x1e\xe311\xa3\x9b\xbe\xd5k\x06\xea"E\'\x98ru-u\xf2\x15\xd3\x00\x9a\xf1`\x12j\x8e\xd5\xdcG\x1cu)\xbb\x9b>e;N_\x8fLY\x1f\x84\'\xa3\xff\x15\x08\xd1`\x03\x92k\xecLq\x8f\x89\xba8E?\x06\x93\x03\xae`.\xd3\x0b\xde\xac\xa7(\xda\xc8\xba(\xb9*\x1b\x85f\xf0\x9d\xd2\x14@3\x9e1%b\x04\xd9\x0c\xe5\xca\x86\xf5\xde\xe3\xca \xb7Tm\xc8\xfe\x91\x8b*\x03\xaa\'\xb1\xc5\xd6o\x1f\x17aW\xdf\x03nY\x0c?\xb6\tsaX\xbd\x8a\xc9\x16\xc0\xfekK\xe1\xb5O\xf3\xe7\xa5\x0f\x05\x16\x16\x85\xc7v\x8a\xb1|N\x0bS\x86aR\xa9"\x1f\xb9\xab\x03C\x82R)\x99\xc2\xa2\xbeh\x04\x18\x97\xac\xd1\x15\x8f\x92\xa1E\x0f\xb5\xdeX.\x99\xe7nH\xf7fa\xdd\x86n\x9f\xf0]aj\xfdy^x\xb03qQD\x1b]\xe6\x11`\xa3\x16\xcb\x93`N\x1a\xab\xc1\x1f\\\xd2\xa7\xf4\xfcb\x84\x1d\xb6\xa9=o|\xba|\x1az\x04\xa6&,YM\xa8%\x0e\xb2\xbdZ&\x81\x11o\x8a\',\xb74N\xf7\x12]\xf1a\xbaz\x1a\x05\\\xc8\x84\x80\xd1M\xb2\x97\x0e\xa4b\xf9I\xccr\xc0\xb9\xeche\n\x92\t\x83\xb5\xb79\x99\xf8\xcb\xaa\x08\xa2\xdd\x8a\x95\x92\x8b\xcc\x8f\xa4s.\xad\xa9\x8a\xb9\xcd\xaey3\xde\x0b\'\xb3vc\xac\xd8Z\x17\x14\x84#\x98\xa5\x93\xa0\x14\xcbp>\xd8%\xadj\x06\x91y\x91~F\x84Z\xed}\xc9\xd2E\xdfh\x8e2\xa1\x87W,B\xbf\xbc\xce-\x96\xc6\xf9\x96}\x97\x98Y\xb8\x1a\xedzY1\rA\xe4 \n\xc9\xa4\xd5\x0cu\xa4\xae\x15KPg\x0f\x89\xfe\xe8+.\xbc\x10\x18\x14\x9a\x9c\xff]ypd\xa4\xbd\xa0\xbbX1\xa5*\x80\xbb\xa1\x1b\xdan\xf8j\x82\xe3\x1f\xbc\x1bJ\xe6\x82\x12\xa5\xf9\x8a\x87\xb86\x88di\xbf\xed\xb7\xd7\xa2\xcf4N\xca\xd5d\xd93C\xc5\xc3\xa5f\xe3\xb2J\x9f\x9c\x1b\xee<\xefD\x9b9<e\x99\xc6\'\xba\xbbi((0\x06\xc32\xab\x82\xc1\xf5\xfe@*p\x80\x03Uh\x9bF\xd0\x8a\xb5\xea\xb4\xccT\xdc\x87\xdb\xc2\xc5\x00\x94\xe6\x10\xb7\xd7|\x99\xd578$5~\xd1`\xb5A\x02\xdf\xb6\xb0\xae\xbe\x0e[gi\x0b\x08\x9c\x06y#\x17t\x1c~9\x07\xdb\x18\xc4\x06\xa250,\x85\x15\xb9\xd7r\\\x1e\x14\x1b3;\x8e\x9c\xbd3\x87\xe3O ul{I_s4\x9c\x01\xae\xf3ACG\xbabk8c2\xda[o1\xf6\xc0`\x08\x8eG\xb9\xa5\'K\x91\xb3\'\xda\xf6\xb0\xd8\x94\x08[\x1dJ\xe7\xe1\x88@\xfb\x82pz\xb5]f\x1e\x0f\xbd\x01\xba\xac\xb3\xaf\xcb\xf1\xc6#\x14\xcb\x13%m\xd0\x99z\xbf\x10\x19\xca\xcd\x04\x87\xb3\x1a\x92$\xa0\xa0\xee]l9WX;6\xa9\xd9\x15.x\xed\x8a\xa1rb\xa5\'\xb7H\xd1{\x96\x9dX\x10(6\xa7Yz\xf8\xd2w0\xe1_\xb3t\x7f3\xc3\xfb\x1f\xbd\x94>\x82\x93\xd0;\xa7,\xa0\xc6\xc5\xc6\x88\x8e\x1a~\xa6\xbe\xd0%\x13\xa6\x04\xc05gt\x92\xa9b\xec\x08\x80\xea95e`\xaeL\x8fl\x16]\xfb}\x8fq9\xa6\x8a7_\x83\x1b\xc7G\xa7\x1c\x83i\xcb\x9e\x0c\x1c\x95\x926\x8c\xd2\xff\xc0\xd43\xec\xf6\xcdW\xdb\xc2\x10^L\x18K]\xb6\xa4\xfdt\x869$`>\xad\xda\x0f\xa7\xfep\xb7\xa8\x94\xfb\xcd\x04\xd7?d\xfd\xbe@k|\x18_a\x1bp\xce\x14\xd4FD\x86\x1a:c+\xb6\x0c \x88\x94\x9c\x01\xe9\xed\xfb\xed2\xb3\xaa\xeb;\x06\xf43\x04\x8b\xad\xb65\xc7Sq\n\xbc\x00\xb2H5\xbdD60\x92I\x10\x80\x89\x98\xfa\x99\xfa\xa0\x81\xef\x13\x05Dlc\xa8\x1fT<\xf7\xb7\xc0\xb3h\xdfT\xe1n\xf8\x16\xac\xff\x1eW\x8b"\xa6\xbb\xc2V\x1fn\x0b\x17\xe9\xd0\xbe\x0f\x14\xd7\x06]+@\x9c\xf3\xcc-\xa3\xc6\x9cLCP\xb9\xe6\x00\xe6Cf\xd0\xea0\xe6\xea\xac\xc7\xae\x13d&dL\xc9J\x8e\xd3\xb6\xea\x84\x83\re,\xc7X0\x9a\xa7\x18H\xf4j\xb6\xc2\xcc\xe1\xaar^+\xdbtL9\x9b\xf2]\xe8\xea\x9ce:RmU\xc2\xcbd%\xcbyr\xe8ez@gRC\xe0\xf9\x9a\t\x10\xd6%\xa9Y\x88\xb7\x1b\xa5\x04\x1bT\xf3Z\x8c\xb8#+\x80\x01\xb4\xb3\n#\xcfF\x14OG\xdb\xbf"=\xc0e)U\x98\x86W\xc8V\x1c\x04\xbeP\x85\xd1\x01\xb0\x7f9\xcdB\x0e:\xd4\x8a\x8e\x98OQZ\x8e\xab\xef\x9f\x0e5\xf2\x10\x91\xaeK;A\xf0@;/tl\xf3\x85w\x85!\x98*\xabb@<d\xf3\xfb\xa2t\xc0\xeb\xc2.*\x93O&\xdb\xa4oK\xf1\xf0#3iP\xd1\xec<\x0c\xebB\x87k\xf7\x00\xfa\xf5\x01R^\x90\x84_\x86R\xf3f\x82\xf1\xb8\x18V\x95\xe8q\xbf\x97\x1fB4\x96b\x07\x19k\xe3\xc4\x8f\x804\xe8}\xba\x8c\xf4\x99[8<\xec0\x1a\x191\xf95\'\x93n\xca\xda\xf8<\x95\x8dm\x02/G~\x007(VQ$\xe6\x03\xbdOU>\x98\xcc*{\x01\xf5]\x9f\x82\xb2sM\xe6\xb1\x80\xd5(KWG\x15H\xb1\x0e\x17\xbb\xb4\x13\xa9%x9c$\xcf\xeev\xa4\xce\x17\xa0\xe6\xbf\x99`\xc9F\xc7\xdd_\x883\x9c}[s\xf9A\x98\xe8@\xf1V1r\xf0\x19\x19\x80\xa7\xcd\x85\x86i\xeb>8\xd0%\x03\x92t\xae\x01.\xc0N\x86!Z\xe0Pg\xb4lN\xce"@\xaa*\xc4\xfd\xc4\xde\xec>@\xef\xceu\x89@Y{\xb4A\x042#>\xc9\xc9Wo\x88{zz\xc5\xd7\xc5\xe3\xad\xec2t\x8a^\xb9\xb8\x14\x9d$\x8aN\x01\xe0\xea\x8a\xf3\xee$\x91\xe5\xc4\xa4\xaa\x0b\x04\\\xcd\x80^\xa6[\xac\xdd\xfc\xf4f\xb6\xac\x95\x9b\xdf\x19&6\x1c\xf8{\xc8M\x99\xe0\x0c\xc3\x19\xeb3\x19\\/J\x97\\\x84\xb0\xb7\xb3\xfe\xab\x82-\xf3\xee%T;\r\xe6\xe5&\xce\xb8d\xda6\xbfs\xf2u\xca\x1cX\x19m\xfc\xd4\xecm\xc0)\xaa\xa9\xc4S\xa763\x1f;\xd6\x0b\xa3M\xc6\x8ee\xb5\xea\xaa|\x10\x8d\xb8AG\xcc\x7f\xbaZ\xaaz\xc3\xaaF\xa3\xb3L\x0c\x13\xa7\xbb\x17\x90\x86\xf2\xda\xb2\xb1&\x06\n|\xacO\xdc\xa4\x81]\x86\xcc+&LLx\x82\xe8\xdf0\x0e{z\xd8,\x8a\x1bB\xdd\xa1\xfe0\x1e40,\xaa\xdf\x0fe{\x16\xf91\x83\x12/\xbdNA\xdc`\xefr4w\xa3bc\x8bP\xf4\x90\xa4j\x1e\xaf\xd7\x1c\x0c;\xa0\x0fT \x83Vq\x0c\xbb\xe2j\xec\x0c\x92\xab\xa9\xadc\xa0\xb7\x99h\xdb\xa7\x0bN\xfdQ\xbe\xa4\xa5\xb3r\xbd35U;.\xf6\xf5\xed\xb7\xc7\xc9\xea\xb2b\xe8D\xea\xafS\xa8\x89\x9e\xfa\xd2\xb0\r]\x0f\xbf^P\x14B\x90\xdf\x8c\x9c\xcb\x8aAI\xd7\xd3\xd7{i\xb5\x91\xd5"\xfch\x9b\xdfy\x00l!\x87\x04*\x0b-\xd6\xd6\xe8\xae0K*]\xdd\xa4\xa3\x82\xae^q\x00\x8e\xcf\x9a\xc6!6\x90%6\xf1it\x16m\x08\xc3\x83\x81\xf5Dgp3\xc5\xb8\rM|\xbd\x16)\xb8\xbal\xc4\xe2\x11\x10\x00$G\xb7"\xb8\x8a\xb1\xceF\xb7ZXim\xca\x08\x92\xa5\x9b\xe2A\x84@N\x0f\x14\x9f\xab\xf2)@\xcc\xed\xe5\xd8\xa0\n\xb6\xcb\xa0I\x830zF\xc9\xea\xed\xd0\xaa%\xa6V)b\xcb\x07\x90\xb5\x0c\x17\xc1\xd1\xa4\x8d\xad\xe9\xf3\xdf3\x0eJia#\xc5\xbbI\xcf\xb3\x0c\x87=\x00\xd9\x9d\x94\x9a\x86G\xf1\x92\xc5\xf6[\x8e;\xca\xc5]]_\xe10\xceT\x9f\xf3\r+=\x88U\x14\xaff\x12\xb5\xc3\xf3s\x05\xd2\xd3\\\xee0\xd2\xa9X\xfc\xe4\xa1\x99\x83l\xb1a\x06Z\x80\x18\xa4\x94F\xde\xb1\xde\xa1\x03k\x9b2\xed\x10p!\xbb\xbd;\xbc\x14\xcf{A.!\x9b\x819e\x9bS\x85\xe4\xcb\x82SEd\xb9\x92\r\xca\x17\xe0\x10>\xb6\xech\xa17\x0c\x05\x1f\x18\xeb\x00\rZU3{/\x9b\'!\x8d\xe3K\xda\x9b9e\x1fm\xd4\xe5qG\xad:\xa9q,\x97\x00\xbf>x0\xcbYc\xa2\xa9\xd8\x8a\xe2t\xd5\x9cQ12\x9c\xaan\xb4\x0cN\x82\x9aTn\xca\xa9\x1ah\xf9\xbc\xa2M\t\xe9x\x8e\xb7\x9e\xeb):BV<\xc0\xaf,\xb2\x82N\xa1\xe2\xcb\x84\xbb\xfea\x99f$\x04P\xacV\xd6L\xdb\xfe\xf3\xa1~\x03q*4\xa54\x13~Jg\\Kj\xd6n\xe9\x11Et\x00\x92\xf6dq8j0\x96\xd2\xd9\x18sS\xff\xa6t\xd0\x90\xa7\x08R\xca\x1c\xe2F\x07\xe6\x12\x8c\xc9\xe5T\xb5\x8fN.K\xc2\x1f\xd0\xc6\xb5>\x90\xd5\xf4|5\x12\xe9D\x88A\xda\xe8*v\xaa\x1d\x94\x1a|\x92\x99\x94j\x89\xc1\x05\x86\xf79\xfa\xac\xd5t\xb7|(\x94\x07T\xa8\xa5o\xb9\xe4\x1a\x1e\x0f\x82\xf26\xab\xbc\xa9\xbeMA\x16i\x1dcA\n]/\x9b\x89\xe0\x13p\xaa\x83\xa3\xdd\xf5HkD\xc1[RA\x8d\x00\x97\x8dyBDA;k\x95\x9adg3L\x1c{\x8bLa\xa3\xb5\xae;\xdc\x97LQt\xc4\x8e\xc8\x98T\xc5\xd7]\x83w\x8b\xc1xY\xb1\xc0\xdd\xb1N6\xc6\x8cw\x9f\xb3\xd9GlB\x07\xeb\xba\xda\x16m\xcd\x1bTH\x93Uu\xde\xc7\x0co?gjO\x81\xe3\xbd\xe5X\x1b\xb6\xfa\xe3W\xea\xa9\xa8\xe4\x94\xe7\x9cv/Y\x16\x1ae/.\xf5\x9b\xee\xbd\x03\x08\\\xc9\xa4\xac\xb5\x15\x0f%\x05\n9Z\xdbD\x91\x86\x9e\xe7,\x8f^\xec\x0e\x11]\xf9~U\x9f,\x8e\x1d\x17\xc8<V\x90\xab\x15:\x1a\xa7\xd8q\xc8\x1dr\xa2a\x07\xab\xff\x94\x9b!6\x17s}\x1aa\x98q\\\x98JDz2\x8f2QH\x12\xd1O<\xe7\x19f\xd2\xe8\xbcjJ\xd0\x81\xdd\x9cqM\x0e\x1b.\x08\x9d%\xf5U\x04\x83p\xea\xd2\x0c\x939\xe49\xf0\x90F\xc4\xd0\\\xd3u\xe9@(+\xf9\x01\x88W\xf3\x17W_\x8f\xd1\xa1\xf8\xabe]Q\xd8h\x9fu\xf6\x98\'\xb0\xa5H\xb2\xe9\xfd\x97\x84\xad\xa2\xa4\xa5\xc9\x08\xb8\xe1Y\xff\x98\xf7\xe8\xd9\x03\x

In [ ]:
import zipfile

# Unzip the file if it's a zip archive
zip_file_path = 'cleaned_air.csv.zip'
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall('.')

# Now open the extracted CSV file
file = open("cleaned_air.csv", "r")
data = file.read()
print(data.split("\n")[:6])   # Display first few rows
file.close()

['Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Landing Aircraft Type,Aircraft Body Type,Aircraft Manufacturer,Aircraft Model,Landing Count,Total Landed Weight', 'SkyWest Airlines,OO,United Airlines,UA,International,Canada,Passenger,Regional Jet,Bombardier,CRJ2,30,1410000', 'Air Canada,AC,Air Canada,AC,International,Canada,Passenger,Narrow Body,Airbus,A320,125,17787978', 'Japan Airlines,JL,Japan Airlines,JL,International,Asia,Passenger,Wide Body,Boeing,B773,30,16620000', '"COPA Airlines, Inc.",CM,"COPA Airlines, Inc.",CM,International,Central America,Passenger,Narrow Body,Boeing,B739,3,491700', 'Hong Kong Airlines Limited,HX,Hong Kong Airlines Limited,HX,International,Asia,Passenger,Wide Body,Airbus,A359,16,7301712']

In [ ]:
import pandas as pd
df = pd.read_csv('cleaned_air.csv')
df[df["Operating Airline"] == "SkyWest Airlines"]

,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Landing Aircraft Type,Aircraft Body Type,Aircraft Manufacturer,Aircraft Model,Landing Count,Total Landed Weight
0,SkyWest Airlines,OO,United Airlines,UA,International,Canada,Passenger,Regional Jet,Bombardier,CRJ2,30,1410000
35,SkyWest Airlines,OO,Alaska Airlines,AS,Domestic,US,Passenger,Regional Jet,Embraer,E175,65,4872205
48,SkyWest Airlines,OO,United Airlines,UA,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ7,208,13936000
54,SkyWest Airlines,OO,United Airlines,UA,International,Canada,Passenger,Regional Jet,Embraer,E175,12,899484
90,SkyWest Airlines,OO,United Airlines,UA,Domestic,US,Passenger,Regional Jet,Embraer,E170,601,45049157
...,...,...,...,...,...,...,...,...,...,...,...,...
22040,SkyWest Airlines,OO,Delta Air Lines,DL,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,155,7285000
22041,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,268,17956000
22042,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,International,Canada,Passenger,Regional Jet,Bombardier,CRJ,62,4154000
22043,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,1360,63920000
22044,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Turbo Prop,Embraer,ERJ,1655,42699000

In [ ]:
df[df["Operating Airline"] == "SkyWest Airlines"]

,Operating Airline,Operating Airline IATA Code,Published Airline,Published Airline IATA Code,GEO Summary,GEO Region,Landing Aircraft Type,Aircraft Body Type,Aircraft Manufacturer,Aircraft Model,Landing Count,Total Landed Weight
0,SkyWest Airlines,OO,United Airlines,UA,International,Canada,Passenger,Regional Jet,Bombardier,CRJ2,30,1410000
35,SkyWest Airlines,OO,Alaska Airlines,AS,Domestic,US,Passenger,Regional Jet,Embraer,E175,65,4872205
48,SkyWest Airlines,OO,United Airlines,UA,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ7,208,13936000
54,SkyWest Airlines,OO,United Airlines,UA,International,Canada,Passenger,Regional Jet,Embraer,E175,12,899484
90,SkyWest Airlines,OO,United Airlines,UA,Domestic,US,Passenger,Regional Jet,Embraer,E170,601,45049157
...,...,...,...,...,...,...,...,...,...,...,...,...
22040,SkyWest Airlines,OO,Delta Air Lines,DL,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,155,7285000
22041,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,268,17956000
22042,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,International,Canada,Passenger,Regional Jet,Bombardier,CRJ,62,4154000
22043,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Regional Jet,Bombardier,CRJ,1360,63920000
22044,SkyWest Airlines,OO,United Airlines - Pre 07/01/2013,UA,Domestic,US,Passenger,Turbo Prop,Embraer,ERJ,1655,42699000

In [ ]:
print("Unique GEO Regions:", df["GEO Region"].unique())
print("Number of Aircraft Body Types:", df["Aircraft Body Type"].nunique())

Unique GEO Regions: ['Canada' 'Asia' 'Central America' 'Europe' 'US' 'Mexico'
 'Australia / Oceania' 'Middle East' 'Caribbean' 'South America']
Number of Aircraft Body Types: 4

In [ ]:
df["Total Landed Weight"].describe()

count    2.204500e+04
mean     1.899138e+07
std      3.033287e+07
min      6.850000e+03
25%      3.035292e+06
50%      9.660000e+06
75%      1.953000e+07
max      2.730420e+08
Name: Total Landed Weight, dtype: float64

In [ ]:
df[df["Total Landed Weight"] > 15000]["Operating Airline"]

0                  SkyWest Airlines
1                        Air Canada
2                    Japan Airlines
3               COPA Airlines, Inc.
4        Hong Kong Airlines Limited
                    ...
22040              SkyWest Airlines
22041              SkyWest Airlines
22042              SkyWest Airlines
22043              SkyWest Airlines
22044              SkyWest Airlines
Name: Operating Airline, Length: 22017, dtype: object

In [ ]:
df[(df["Total Landed Weight"] >= 20000000) & (df["Total Landed Weight"] <= 40000000)]["Operating Airline"]

15                    Emirates
17                  Air France
20             Virgin Atlantic
28             United Airlines
52           American Airlines
                 ...
22011           Japan Airlines
22026    Nippon Cargo Airlines
22029       Northwest Airlines
22030       Northwest Airlines
22037       Singapore Airlines
Name: Operating Airline, Length: 2709, dtype: object